 clc
 clear all
 close all
%% notation
%row=vertical=t,x
%col=horizontal=s,y

%% IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 19-Jun-2012 11:37:02

% Import the file
fileToRead1='..\..\test_modelsim.txt';
newData1 = importdata(fileToRead1);

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end

%% input data
teta=60/180*pi;
HorResOut=800;
VerResOut=600;
XSizeIn=96;
YSizeIn=128;
Xstart=30;
Ystart=29;
m=XSizeIn+1-Xstart;%m=67
n=YSizeIn+1-Ystart;%n=100
ZoomFactor=0.25;

img=imread('lena128.jpg');
Img=zeros(1,128*96);
Img=reshape(img,1,128*96);%----------------need fix


ImOut=uint8(zeros(600,800));
% operating zoom, rotation, resolution change. 
%x=0;
for row=1:VerResOut-1%:-1:1
   for col=1:HorResOut-1 %:-1:1
       index=col+(row-1)*800;
       out_of_range=data(index,9);
       if out_of_range==0 
            if data(index,3)~=0 && data(index,4)~=0 && data(index,5)~=0 && data(index,6)~=0 && data(index,3)<12289 && data(index,4)<12289 && data(index,5)<12289 && data(index,6)<12289
            %x=x+1;
            top_left=Img(data(index,3));
            top_right=Img(data(index,4));
            bottom_left=Img(data(index,5));
            bottom_right=Img(data(index,6));
            deltaJ=data(index,8)/128;
            deltaI=data(index,7)/128;
        
            I1=(1-deltaJ)*top_left+deltaJ*top_right;%weighted avarage between two bottom pixels
            I2=(1-deltaJ)*bottom_left+deltaJ*bottom_right;%weighted avarage between two top pixels
            ImOut(row,col,:)=(1-deltaI)*I1+deltaI*I2;%weighted avarage between two values  avaraged values
            
            end
       end
   end
end

subplot(1,2,1)
imshow(ImOut',[])%  need to remove transpose and fix line 38, the image is read coloums, should be rows first
title('output');
subplot(1,2,2)
imshow(img,[])
title('original');
